[package]
name = "crates_bot"
version = "0.1.0"
authors = ["Gustavo Aguiar <gugahoa@gmail.com>"]

[dependencies]
telebot = { git = "https://github.com/gugahoa/telebot", branch = "inline_improvements" }
erased-serde = "0.3"
futures = "0.1.7"
tokio-core = "0.1.2"
crates_api = { path = "crates_api" }

[workspace]
