[package]
name = "crates_bot"
version = "0.1.0"
authors = ["Gustavo Aguiar <gugahoa@gmail.com>"]
edition = "2018"

[dependencies]
telegram-bot = { path = "../../telegram-rs/telegram-bot/lib" }
erased-serde = "0.3"
futures = "0.1.7"
tokio-core = "0.1.2"
crates_api = { path = "crates_api" }

[workspace]
